/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, clang++ 18.1.8 -fPIC -O3) */

module \$paramod\clk_divider\DIV_RATIO=s32'00000000000000000000000000000010 (clk_in, rst_n, clk_out);
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input clk_in;
  wire clk_in;
  output clk_out;
  reg clk_out;
  reg [-1:0] \genblk1.even_div.cnt ;
  input rst_n;
  wire rst_n;
  assign _06_ = ~_07_;
  assign _05_ = _09_ | _08_;
  assign _03_ = _09_ & ~(_08_);
  assign _04_ = _09_ ^ _08_;
  always @(posedge clk_in, negedge rst_n)
    if (!rst_n) \genblk1.even_div.cnt [-1] <= 1'h0;
    else \genblk1.even_div.cnt [-1] <= _00_[0];
  always @(posedge clk_in, negedge rst_n)
    if (!rst_n) \genblk1.even_div.cnt [0] <= 1'h0;
    else \genblk1.even_div.cnt [0] <= _00_[1];
  always @(posedge clk_in, negedge rst_n)
    if (!rst_n) clk_out <= 1'h0;
    else if (!_01_) clk_out <= _02_;
  assign _09_ = \genblk1.even_div.cnt [-1];
  assign _08_ = \genblk1.even_div.cnt [0];
  assign _01_ = _05_;
  assign _00_[0] = _03_;
  assign _00_[1] = _04_;
  assign _07_ = clk_out;
  assign _02_ = _06_;
endmodule

module domain_a_cmd_fsm(clk_core, rst_n, cmd_valid, cmd_data, cmd_ack, fsm_state);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire [7:0] _070_;
  wire [7:0] _071_;
  wire [7:0] _072_;
  wire [7:0] _073_;
  wire [5:0] _074_;
  wire clk_150;
  input clk_core;
  wire clk_core;
  input cmd_ack;
  wire cmd_ack;
  reg [7:0] cmd_counter;
  output [7:0] cmd_data;
  wire [7:0] cmd_data;
  wire [7:0] cmd_data_r;
  output cmd_valid;
  wire cmd_valid;
  reg cmd_valid_r;
  output [1:0] fsm_state;
  wire [1:0] fsm_state;
  reg [7:0] heartbeat_counter;
  wire [1:0] next_state;
  input rst_n;
  wire rst_n;
  wire rst_n_core;
  reg [1:0] state;
  assign _027_ = ~_044_;
  assign _019_ = ~_036_;
  assign _067_ = _068_ & ~(_069_);
  assign _052_ = _069_ & ~(_035_);
  assign _065_ = ~(_068_ | _052_);
  assign _066_ = _068_ ^ _069_;
  assign _053_ = _044_ & _045_;
  assign _028_ = _044_ ^ _045_;
  assign _054_ = _046_ & _053_;
  assign _029_ = _046_ ^ _053_;
  assign _055_ = _047_ & _054_;
  assign _030_ = _047_ ^ _054_;
  assign _056_ = _048_ & _055_;
  assign _031_ = _048_ ^ _055_;
  assign _057_ = _049_ & _056_;
  assign _032_ = _049_ ^ _056_;
  assign _058_ = ~(_050_ & _057_);
  assign _033_ = _050_ ^ _057_;
  assign _034_ = ~(_051_ ^ _058_);
  assign _059_ = _036_ & _037_;
  assign _020_ = _036_ ^ _037_;
  assign _060_ = _038_ & _059_;
  assign _021_ = _038_ ^ _059_;
  assign _061_ = _039_ & _060_;
  assign _022_ = _039_ ^ _060_;
  assign _062_ = _040_ & _061_;
  assign _023_ = _040_ ^ _061_;
  assign _063_ = _041_ & _062_;
  assign _024_ = _041_ ^ _062_;
  assign _064_ = ~(_042_ & _063_);
  assign _025_ = _042_ ^ _063_;
  assign _026_ = ~(_043_ ^ _064_);
  always @(posedge clk_core, negedge rst_n_core)
    if (!rst_n_core) cmd_counter[0] <= 1'h0;
    else if (_074_[5]) cmd_counter[0] <= _070_[0];
  always @(posedge clk_core, negedge rst_n_core)
    if (!rst_n_core) cmd_counter[1] <= 1'h0;
    else if (_074_[5]) cmd_counter[1] <= _071_[1];
  always @(posedge clk_core, negedge rst_n_core)
    if (!rst_n_core) cmd_counter[2] <= 1'h0;
    else if (_074_[5]) cmd_counter[2] <= _071_[2];
  always @(posedge clk_core, negedge rst_n_core)
    if (!rst_n_core) cmd_counter[3] <= 1'h0;
    else if (_074_[5]) cmd_counter[3] <= _071_[3];
  always @(posedge clk_core, negedge rst_n_core)
    if (!rst_n_core) cmd_counter[4] <= 1'h0;
    else if (_074_[5]) cmd_counter[4] <= _071_[4];
  always @(posedge clk_core, negedge rst_n_core)
    if (!rst_n_core) cmd_counter[5] <= 1'h0;
    else if (_074_[5]) cmd_counter[5] <= _071_[5];
  always @(posedge clk_core, negedge rst_n_core)
    if (!rst_n_core) cmd_counter[6] <= 1'h0;
    else if (_074_[5]) cmd_counter[6] <= _071_[6];
  always @(posedge clk_core, negedge rst_n_core)
    if (!rst_n_core) cmd_counter[7] <= 1'h0;
    else if (_074_[5]) cmd_counter[7] <= _071_[7];
  always @(posedge clk_core, negedge rst_n_core)
    if (!rst_n_core) state[0] <= 1'h0;
    else state[0] <= next_state[0];
  always @(posedge clk_core, negedge rst_n_core)
    if (!rst_n_core) state[1] <= 1'h0;
    else state[1] <= next_state[1];
  always @(posedge clk_core, negedge rst_n_core)
    if (!rst_n_core) cmd_valid_r <= 1'h0;
    else cmd_valid_r <= _074_[5];
  always @(posedge clk_150, negedge rst_n)
    if (!rst_n) heartbeat_counter[0] <= 1'h0;
    else heartbeat_counter[0] <= _072_[0];
  always @(posedge clk_150, negedge rst_n)
    if (!rst_n) heartbeat_counter[1] <= 1'h0;
    else heartbeat_counter[1] <= _073_[1];
  always @(posedge clk_150, negedge rst_n)
    if (!rst_n) heartbeat_counter[2] <= 1'h0;
    else heartbeat_counter[2] <= _073_[2];
  always @(posedge clk_150, negedge rst_n)
    if (!rst_n) heartbeat_counter[3] <= 1'h0;
    else heartbeat_counter[3] <= _073_[3];
  always @(posedge clk_150, negedge rst_n)
    if (!rst_n) heartbeat_counter[4] <= 1'h0;
    else heartbeat_counter[4] <= _073_[4];
  always @(posedge clk_150, negedge rst_n)
    if (!rst_n) heartbeat_counter[5] <= 1'h0;
    else heartbeat_counter[5] <= _073_[5];
  always @(posedge clk_150, negedge rst_n)
    if (!rst_n) heartbeat_counter[6] <= 1'h0;
    else heartbeat_counter[6] <= _073_[6];
  always @(posedge clk_150, negedge rst_n)
    if (!rst_n) heartbeat_counter[7] <= 1'h0;
    else heartbeat_counter[7] <= _073_[7];
  \$paramod\clk_divider\DIV_RATIO=s32'00000000000000000000000000000010  u_div150 (
    .clk_in(clk_core),
    .clk_out(clk_150),
    .rst_n(rst_n)
  );
  reset_sync u_rst_core (
    .async_rst_n(rst_n),
    .clk(clk_core),
    .sync_rst_n(rst_n_core)
  );
  assign _070_[7:1] = cmd_counter[7:1];
  assign _071_[0] = _070_[0];
  assign _072_[7:1] = heartbeat_counter[7:1];
  assign _073_[0] = _072_[0];
  assign { _074_[4], _074_[1:0] } = 3'h0;
  assign cmd_data = cmd_counter;
  assign cmd_data_r = cmd_counter;
  assign cmd_valid = cmd_valid_r;
  assign fsm_state = state;
  assign _044_ = heartbeat_counter[0];
  assign _072_[0] = _027_;
  assign _036_ = cmd_counter[0];
  assign _070_[0] = _019_;
  assign _068_ = state[0];
  assign _069_ = state[1];
  assign _074_[5] = _067_;
  assign _035_ = cmd_ack;
  assign next_state[0] = _065_;
  assign next_state[1] = _066_;
  assign _045_ = heartbeat_counter[1];
  assign _073_[1] = _028_;
  assign _046_ = heartbeat_counter[2];
  assign _073_[2] = _029_;
  assign _047_ = heartbeat_counter[3];
  assign _073_[3] = _030_;
  assign _048_ = heartbeat_counter[4];
  assign _073_[4] = _031_;
  assign _049_ = heartbeat_counter[5];
  assign _073_[5] = _032_;
  assign _050_ = heartbeat_counter[6];
  assign _073_[6] = _033_;
  assign _051_ = heartbeat_counter[7];
  assign _073_[7] = _034_;
  assign _037_ = cmd_counter[1];
  assign _071_[1] = _020_;
  assign _038_ = cmd_counter[2];
  assign _071_[2] = _021_;
  assign _039_ = cmd_counter[3];
  assign _071_[3] = _022_;
  assign _040_ = cmd_counter[4];
  assign _071_[4] = _023_;
  assign _041_ = cmd_counter[5];
  assign _071_[5] = _024_;
  assign _042_ = cmd_counter[6];
  assign _071_[6] = _025_;
  assign _043_ = cmd_counter[7];
  assign _071_[7] = _026_;
endmodule

module reset_sync(clk, async_rst_n, sync_rst_n);
  input async_rst_n;
  wire async_rst_n;
  input clk;
  wire clk;
  reg rst_ff1;
  output sync_rst_n;
  reg sync_rst_n;
  always @(posedge clk, negedge async_rst_n)
    if (!async_rst_n) rst_ff1 <= 1'h0;
    else rst_ff1 <= 1'h1;
  always @(posedge clk, negedge async_rst_n)
    if (!async_rst_n) sync_rst_n <= 1'h0;
    else sync_rst_n <= rst_ff1;
endmodule
