"""
Nebula SoC - Parameterized N-tap FIR filter RTL generator.

Generates a fully-pipelined balanced adder-tree FIR filter, with one
pipeline register after EVERY tree level (not just one or two, as in
the 16-tap hand-written version). This is a deliberate scalability
decision: as tap count grows, the adder tree gets deeper (log2(N)
levels), and registering every level guarantees each stage's
combinational depth stays bounded and timing-safe regardless of N,
rather than accumulating multiple un-pipelined levels between
registers (which is exactly the bug pattern that caused our original
timing violations at just 16 taps with only 1-2 pipeline stages).

Usage: python3 generate_fir.py <num_taps> <output_file>
       num_taps must be a power of 2 (16, 32, 64, 128, ...)
"""

import sys
import math


def generate_taps(n):
    """Generate a simple symmetric triangular-window-like tap set,
    scaled similarly to the original 16-tap design's coefficients."""
    taps = []
    half = n // 2
    for i in range(n):
        # Triangular shape, peak in the middle, mirrors original style
        dist_from_edge = min(i, n - 1 - i)
        val = 128 * (dist_from_edge + 1)
        taps.append(val)
    return taps


def generate_fir(n, module_name="domain_c_dsp_fir"):
    if n & (n - 1) != 0:
        raise ValueError(f"num_taps must be a power of 2, got {n}")

    levels = int(math.log2(n))
    taps = generate_taps(n)

    lines = []
    lines.append("// ============================================================")
    lines.append(f"// Domain C: DSP Pipeline - {n}-tap FIR Filter (auto-generated)")
    lines.append("// Clock: clk_dsp (250MHz master) + gen_clk_50 (divided /5)")
    lines.append("// Function: Direct-form FIR filter, 24-bit signed samples")
    lines.append("//")
    lines.append("// GENERATED by scripts/generate_fir.py -- fully pipelined")
    lines.append("// balanced adder tree, ONE pipeline register per tree level")
    lines.append(f"// ({levels} levels for {n} taps), for guaranteed timing-safe")
    lines.append("// scaling regardless of tap count.")
    lines.append("// ============================================================")
    lines.append(f"module {module_name} (")
    lines.append("    input  wire                  clk_dsp,")
    lines.append("    input  wire                  rst_n,")
    lines.append("")
    lines.append("    input  wire signed [23:0]    sample_in,")
    lines.append("    input  wire                  sample_valid,")
    lines.append("")
    lines.append("    output reg  signed [23:0]    result_out,")
    lines.append("    output reg                   result_valid")
    lines.append(");")
    lines.append("")
    lines.append("    wire clk_50;")
    lines.append("    clk_divider #(.DIV_RATIO(5)) u_div50 (")
    lines.append("        .clk_in  (clk_dsp),")
    lines.append("        .rst_n   (rst_n),")
    lines.append("        .clk_out (clk_50)")
    lines.append("    );")
    lines.append("")
    lines.append("    wire rst_n_dsp;")
    lines.append("    reset_sync u_rst_dsp (")
    lines.append("        .clk         (clk_dsp),")
    lines.append("        .async_rst_n (rst_n),")
    lines.append("        .sync_rst_n  (rst_n_dsp)")
    lines.append("    );")
    lines.append("")

    # Tap coefficients
    for i, t in enumerate(taps):
        lines.append(f"    localparam signed [15:0] TAP{i} = 16'sd{t};")
    lines.append("")

    # Delay line
    lines.append(f"    reg signed [23:0] delay [0:{n-1}];")
    lines.append("    integer i;")
    lines.append("")
    lines.append("    always @(posedge clk_dsp or negedge rst_n_dsp) begin")
    lines.append("        if (!rst_n_dsp) begin")
    lines.append(f"            for (i = 0; i < {n}; i = i + 1)")
    lines.append("                delay[i] <= 24'sd0;")
    lines.append("        end else if (sample_valid) begin")
    lines.append("            delay[0] <= sample_in;")
    lines.append(f"            for (i = 1; i < {n}; i = i + 1)")
    lines.append("                delay[i] <= delay[i-1];")
    lines.append("        end")
    lines.append("    end")
    lines.append("")

    # Partial products (multiply)
    lines.append("    // ---- Partial products ----")
    for i in range(n):
        lines.append(f"    wire signed [39:0] p{i} = delay[{i}] * TAP{i};")
    lines.append("")

    # Build the pipelined adder tree, level by level
    cur_width = 40
    cur_names = [f"p{i}" for i in range(n)]

    for level in range(1, levels + 1):
        next_width = cur_width + 1
        next_count = len(cur_names) // 2
        sum_names = []
        lines.append(f"    // ---- Level {level}: {len(cur_names)} -> {next_count} ----")
        for i in range(next_count):
            a = cur_names[2 * i]
            b = cur_names[2 * i + 1]
            sname = f"s{level}_{i}"
            lines.append(f"    wire signed [{next_width-1}:0] {sname} = {a} + {b};")
            sum_names.append(sname)
        lines.append("")

        # Pipeline register after every level
        reg_names = [f"reg_{name}" for name in sum_names]
        lines.append(f"    // ---- Pipeline register after level {level} ----")
        lines.append(f"    reg signed [{next_width-1}:0] " + ", ".join(reg_names) + ";")
        lines.append(f"    reg valid_stage{level};")
        lines.append("")
        lines.append("    always @(posedge clk_dsp or negedge rst_n_dsp) begin")
        lines.append("        if (!rst_n_dsp) begin")
        for rn in reg_names:
            lines.append(f"            {rn} <= {next_width}'sd0;")
        lines.append(f"            valid_stage{level} <= 1'b0;")
        lines.append("        end else begin")
        for rn, sn in zip(reg_names, sum_names):
            lines.append(f"            {rn} <= {sn};")
        prev_valid = "sample_valid" if level == 1 else f"valid_stage{level-1}"
        lines.append(f"            valid_stage{level} <= {prev_valid};")
        lines.append("        end")
        lines.append("    end")
        lines.append("")

        cur_names = reg_names
        cur_width = next_width

    final_sum = cur_names[0]
    lines.append("    // ---- Final output register ----")
    lines.append("    always @(posedge clk_dsp or negedge rst_n_dsp) begin")
    lines.append("        if (!rst_n_dsp) begin")
    lines.append("            result_out   <= 24'sd0;")
    lines.append("            result_valid <= 1'b0;")
    lines.append("        end else begin")
    shift_amount = cur_width - 24 - 8  # rough scaling shift, keep similar to original [39:16] pattern
    hi = cur_width - 1 - 8
    lo = hi - 23
    lines.append(f"            result_out   <= {final_sum}[{hi}:{lo}];")
    lines.append(f"            result_valid <= valid_stage{levels};")
    lines.append("        end")
    lines.append("    end")
    lines.append("")

    lines.append("    wire sample_valid_sync;")
    lines.append("    sync_2ff #(.WIDTH(1)) u_sync_sample_valid (")
    lines.append("        .clk      (clk_50),")
    lines.append("        .rst_n    (rst_n),")
    lines.append("        .async_in (sample_valid),")
    lines.append("        .sync_out (sample_valid_sync)")
    lines.append("    );")
    lines.append("")
    lines.append('    (* keep = "true" *) reg [15:0] sample_counter;')
    lines.append("    always @(posedge clk_50 or negedge rst_n) begin")
    lines.append("        if (!rst_n)")
    lines.append("            sample_counter <= 16'd0;")
    lines.append("        else if (sample_valid_sync)")
    lines.append("            sample_counter <= sample_counter + 16'd1;")
    lines.append("    end")
    lines.append("")
    lines.append("endmodule")

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python3 generate_fir.py <num_taps> <output_file>")
        sys.exit(1)
    n = int(sys.argv[1])
    outfile = sys.argv[2]
    rtl = generate_fir(n)
    with open(outfile, "w") as f:
        f.write(rtl)
    print(f"Generated {n}-tap FIR ({int(math.log2(n))} pipeline levels) -> {outfile}")
